[tool.towncrier]
directory = '.'
filename = '../../CHANGELOG.md'
package = 'mbed_cloud'
template = 'template.rst'
title_format = '{version} ({project_date})'
start_string = """
[//]: # (begin_release_notes)
"""
